services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: tc2-web
    env_file:
      - ./apps/web/.env
    ports:
      - '4000:3000'
    depends_on:
      - api-gateway
    networks:
      - challenge-network

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: tc2-api-gateway
    restart: always
    env_file:
      - ./apps/api-gateway/.env
    ports:
      - '4001:3001'
    depends_on:
      - auth-service
      - tasks-service
      - notifications-service
    networks:
      - challenge-network

  auth-service:
    build:
      context: .
    	dockerfile: ./apps/auth-service/Dockerfile
    container_name: tc2-auth-service
    restart: always
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network

  tasks-service:
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
    container_name: tc2-tasks-service
    restart: always
    env_file:
      - ./apps/tasks-service/.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network

  notifications-service:
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
    container_name: tc2-notifications-service
    restart: always
    env_file:
      - ./apps/notifications-service/.env
    ports:
      - '4004:3004'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - challenge-network

  db:
    image: postgres:17.5-alpine3.21
    container_name: tc2-db
    restart: always
    ports:
      - '55432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge_db
    volumes:
      - tc2_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - challenge-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: tc2-rabbitmq
    restart: always
    ports:
      - '5673:5672'
      - '15673:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - tc2_rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD-SHELL', 'rabbitmqctl status']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - challenge-network

volumes:
  tc2_postgres_data:
  tc2_rabbitmq_data:

networks:
  challenge-network:
    driver: bridge
